### ISSUE TITLE
NPE in generation in specific example repo

### ISSUE THREAD

**Issue by ktoso** [ktoso/sbt-jmh#134]
https://github.com/imarios/jmh-benchmarking

**Comment by ktoso** [comment]
via @imarios

**Comment by jiminhsieh** [comment]
After I did a little investigation. I thought this NPE came from `jmh` instead of `sbt-jmh`.

`jmh-gradle-plugin` has the same issue. Here is the issue - https://github.com/melix/jmh-gradle-plugin/issues/91. 

I did experiment for https://github.com/imarios/jmh-benchmarking. I got the same result.
```
Annotation generator had thrown the exception.
java.lang.NullPointerException
	at org.openjdk.jmh.generators.reflection.RFClassInfo.getPackageName(RFClassInfo.java:51)
	at org.openjdk.jmh.generators.core.BenchmarkGenerator.validateBenchmark(BenchmarkGenerator.java:227)
	at org.openjdk.jmh.generators.core.BenchmarkGenerator.generate(BenchmarkGenerator.java:81)
```
After I read to [this line](http://hg.openjdk.java.net/code-tools/jmh/file/1ddf31f810a3/jmh-generator-reflection/src/main/java/org/openjdk/jmh/generators/reflection/RFClassInfo.java#l51) in jmh. `jmh` tries to get the instance of `Package` from `klass`. jmh has the assumption that class under named package instread of [unnamed package](https://docs.oracle.com/javase/specs/jls/se8/html/jls-7.html#jls-7.4.2).

@imarios You could put the class under your package instread of default package, then this issue won't hapen again.

**Comment by retronym** [comment]
I've submitted a fix to JMH for this to give a better error message: https://github.com/openjdk/jmh/pull/38/files
