### ISSUE TITLE
Launching Akka ActorSystem

### ISSUE THREAD

**Issue by alexander-myltsev** [ktoso/sbt-jmh#43]
Hi guys, 

I know that it is not the best place to ask about ActorSystem in JMH, but I believe the right people are here. 

```scala
@BenchmarkMode(Array(Mode.AverageTime))
@OutputTimeUnit(TimeUnit.MICROSECONDS)
@State(Scope.Benchmark)
@Warmup(iterations = 8)
@Measurement(iterations = 4)
@Threads(1)
@Fork(1)
class HandlerBenchmark {
  implicit val actorServiceAskTimeout = Timeout(5.seconds)

  val config   = ConfigLoader.load
  implicit val system = ActorSystem("HandlerBenchmarkActorSystem", config)
  runActors(config)

  @TearDown
  def teardown() = this.synchronized {
    system.shutdown()
  }
}
```

But `teardown` does not work as I see those messages:
```
[info] <JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 24 seconds more...>
[info] <JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 19 seconds more...>
[info] <JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 14 seconds more...>
```

Could you recommend a best practice in what way you do it?

**Comment by ktoso** [comment]
Hello there @alexander-myltsev,
this is a pretty good place to ask this question :-)
We use sbt-jmh in the Akka project as well (in fact, sbt-jmh was created because Akka needed it).

Here's an example (from akka-persistence) where we use jmh for a "large" benchmark, which does use the ActorSystem: https://github.com/akka/akka/blob/master/akka-bench-jmh/src/main/scala/akka/persistence/PersistenceActorDeferBenchmark.scala

What you're missing is that in `teardown` you should call `system.awaitTermination()` because just calling `shutdown()` is an asynchronous operation. Also, instead of creating the actor system in the constructor do this in the `setup` method instead. This way you can change the level on which it should be started/stopped (once per iteration / batch etc).

The `runActors` method also seems a bit weird, are you sure this is the right thing?

**General warning** benchmarking anything that is asynchronous within JMH benchmarks is rather tricky. You need to *really* make sure you measure the right thing, and not some locks contention for example. Having that said, trust no one - bench everything :-)

Happy hakking!

**Comment by alexander-myltsev** [comment]
Thanks for useful link. Everything worked out properly!

**Comment by ktoso** [comment]
Excellent! Happy weekend hakking! :-)

**Comment by alexander-myltsev** [comment]
Same to you, Konrad!
