### ISSUE TITLE
Release for 2.12.0-RC2

### ISSUE THREAD

**Issue by BennyHill** [ktoso/sbt-jmh#89]
Please can we have a release for 2.12.0-RC2?

**Comment by ktoso** [comment]
Hi Benny, thanks for the ping!
Sure, I'd release for 2.12-RC2 but... I don't see why that would be needed?

See here: https://github.com/ktoso/sbt-jmh/tree/master/sbt-jmh-tester "just works"™ with Scala 2.12.0-RC2 :-)

The only part of sbt-jmh that is in scala is the plugin, so that does not change when a project moves to 2.12 - just the scala used by the project changes, not by the build. The extras project is written in pure java so no need on a scala dependent release.

Please upgrade to the latest (in which I fixed extras to be pure java), and it'll just work :)

**Comment by BennyHill** [comment]
Hey, well if it "just works"... let's just go for it!! Sorry for the noise, btw

cc/ @travisbrown
